In [2]:
import numpy as np

In [ ]:
from time import process_time

In [10]:
python_list= [i for i in range(10000)]
start_time=process_time()
python_list= [i+5 for i python_list]
end_time=process_time()
print(end time-start_time)

SyntaxError: ignored

In [11]:
np_array=np.array([i for i in range(10000)])
start_time=process_time
np_array+=5
end_time=process_time()
print(end_time-start_time)

NameError: ignored

In [12]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)


[[1 2 3 4]
 [5 6 7 8]]


In [15]:
a=np.array([23,45,67,89])
print(a)

[23 45 67 89]


In [16]:
b.shape

(2, 4)

In [20]:
#create a numpy array of zeros
x=np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
z = np.full((5,4),1)
print(z)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [23]:
a=np.eye(6)
print(a)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [25]:
b=np.random.random((3,4))
print(b)

[[0.08308505 0.12639859 0.7635227  0.48337315]
 [0.76988766 0.08449253 0.93719371 0.44011514]
 [0.63715696 0.19195677 0.517902   0.20409681]]
